<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Agente;
use Carbon\Carbon;

class AgenteSeeder extends Seeder
{
    public function run(): void
    {
        $agentes = [
            [
                'codigo_agente'       => 'AGT-001',
                'nombres'             => 'Carlos Enrique',
                'apellidos'           => 'Quispe Mamani',
                'email'               => 'carlos.quispe@teamtours.pe',
                'celular'             => '+51 987 654 321',
                'telefono'            => '084-223456',
                'dni'                 => '45678901',
                'fecha_nacimiento'    => '1990-03-15',
                'ciudad'              => 'Cusco',
                'departamento'        => 'Ventas',
                'genero'              => 'masculino',
                'comision_porcentaje' => 8.00,
                'fecha_ingreso'       => '2021-01-10',
            ],
            [
                'codigo_agente'       => 'AGT-002',
                'nombres'             => 'María Fernanda',
                'apellidos'           => 'Huanca Ccopa',
                'email'               => 'maria.huanca@teamtours.pe',
                'celular'             => '+51 976 543 210',
                'telefono'            => '084-224567',
                'dni'                 => '52341678',
                'fecha_nacimiento'    => '1993-07-22',
                'ciudad'              => 'Cusco',
                'departamento'        => 'Ventas',
                'genero'              => 'femenino',
                'comision_porcentaje' => 8.00,
                'fecha_ingreso'       => '2021-03-01',
            ],
            [
                'codigo_agente'       => 'AGT-003',
                'nombres'             => 'José Luis',
                'apellidos'           => 'Condori Apaza',
                'email'               => 'jose.condori@teamtours.pe',
                'celular'             => '+51 965 432 109',
                'telefono'            => null,
                'dni'                 => '48923745',
                'fecha_nacimiento'    => '1988-11-05',
                'ciudad'              => 'Puno',
                'departamento'        => 'Corporativo',
                'genero'              => 'masculino',
                'comision_porcentaje' => 10.00,
                'fecha_ingreso'       => '2020-06-15',
            ],
            [
                'codigo_agente'       => 'AGT-004',
                'nombres'             => 'Ana Lucía',
                'apellidos'           => 'Flores Ttito',
                'email'               => 'ana.flores@teamtours.pe',
                'celular'             => '+51 954 321 098',
                'telefono'            => '084-225678',
                'dni'                 => '61234789',
                'fecha_nacimiento'    => '1995-04-18',
                'ciudad'              => 'Cusco',
                'departamento'        => 'Ventas',
                'genero'              => 'femenino',
                'comision_porcentaje' => 8.50,
                'fecha_ingreso'       => '2022-02-14',
            ],
            [
                'codigo_agente'       => 'AGT-005',
                'nombres'             => 'Roberto Alonso',
                'apellidos'           => 'Cárdenas Villanueva',
                'email'               => 'roberto.cardenas@teamtours.pe',
                'celular'             => '+51 943 210 987',
                'telefono'            => '01-3456789',
                'dni'                 => '43210987',
                'fecha_nacimiento'    => '1985-09-30',
                'ciudad'              => 'Lima',
                'departamento'        => 'Corporativo',
                'genero'              => 'masculino',
                'comision_porcentaje' => 12.00,
                'fecha_ingreso'       => '2019-08-01',
            ],
            [
                'codigo_agente'       => 'AGT-006',
                'nombres'             => 'Lucía del Pilar',
                'apellidos'           => 'Vargas Espinoza',
                'email'               => 'lucia.vargas@teamtours.pe',
                'celular'             => '+51 932 109 876',
                'telefono'            => null,
                'dni'                 => '70123456',
                'fecha_nacimiento'    => '1997-12-01',
                'ciudad'              => 'Arequipa',
                'departamento'        => 'Ventas',
                'genero'              => 'femenino',
                'comision_porcentaje' => 7.50,
                'fecha_ingreso'       => '2023-01-09',
            ],
            [
                'codigo_agente'       => 'AGT-007',
                'nombres'             => 'Miguel Ángel',
                'apellidos'           => 'Puma Huillca',
                'email'               => 'miguel.puma@teamtours.pe',
                'celular'             => '+51 921 098 765',
                'telefono'            => '084-226789',
                'dni'                 => '55678234',
                'fecha_nacimiento'    => '1991-06-14',
                'ciudad'              => 'Cusco',
                'departamento'        => 'Operaciones',
                'genero'              => 'masculino',
                'comision_porcentaje' => 9.00,
                'fecha_ingreso'       => '2020-11-20',
            ],
            [
                'codigo_agente'       => 'AGT-008',
                'nombres'             => 'Claudia Patricia',
                'apellidos'           => 'Soto Herrera',
                'email'               => 'claudia.soto@teamtours.pe',
                'celular'             => '+51 910 987 654',
                'telefono'            => '01-4567890',
                'dni'                 => '47891234',
                'fecha_nacimiento'    => '1989-02-27',
                'ciudad'              => 'Lima',
                'departamento'        => 'Corporativo',
                'genero'              => 'femenino',
                'comision_porcentaje' => 11.00,
                'fecha_ingreso'       => '2018-05-07',
            ],
            [
                'codigo_agente'       => 'AGT-009',
                'nombres'             => 'Diego Armando',
                'apellidos'           => 'Zuñiga Inca',
                'email'               => 'diego.zuniga@teamtours.pe',
                'celular'             => '+51 909 876 543',
                'telefono'            => null,
                'dni'                 => '63456789',
                'fecha_nacimiento'    => '1994-08-10',
                'ciudad'              => 'Cusco',
                'departamento'        => 'Ventas',
                'genero'              => 'masculino',
                'comision_porcentaje' => 8.00,
                'fecha_ingreso'       => '2022-07-18',
            ],
            [
                'codigo_agente'       => 'AGT-010',
                'nombres'             => 'Paola Cristina',
                'apellidos'           => 'Mamani Torres',
                'email'               => 'paola.mamani@teamtours.pe',
                'celular'             => '+51 898 765 432',
                'telefono'            => '054-345678',
                'dni'                 => '58901234',
                'fecha_nacimiento'    => '1992-05-03',
                'ciudad'              => 'Arequipa',
                'departamento'        => 'Ventas',
                'genero'              => 'femenino',
                'comision_porcentaje' => 8.50,
                'fecha_ingreso'       => '2021-09-01',
            ],
        ];

        foreach ($agentes as $data) {
            Agente::create(array_merge($data, [
                'pais'   => 'Perú',
                'estado' => 'activo',
            ]));
        }
    }
}
